import BNC_CONFIG

ALLOWED_DIGITAL_3V3_OUTPUT_PINS = [
    BNC_CONFIG.P_SYNC_OUT_TO_LD,
    BNC_CONFIG.P_TDC_OUT_TO_LD,
    BNC_CONFIG.P_USER2_OUT_TO_LD,
    BNC_CONFIG.P_TDC_LED_TO_LD,
    BNC_CONFIG.P_USER1_OUT_TO_LD,
    BNC_CONFIG.P_REF_OUT_TO_LD,
    BNC_CONFIG.P_VETO_OUT_TO_LD,
    BNC_CONFIG.OE_LD,
    BNC_CONFIG.B_USER1_BI_DIR_L3V3,
    BNC_CONFIG.B_USER2_BI_DIR_L3V3,
    BNC_CONFIG.OE_LS,
    BNC_CONFIG.DIR_L3,
    BNC_CONFIG.B_SYNC_IN_TO_EUT_L3V3,
    BNC_CONFIG.B_REF_IN_TO_EUT_L3V3
]

ALLOWED_DIGITAL_3V3_INPUT_PINS = [
    BNC_CONFIG.P_USER2_IN_TO_BBB,
    BNC_CONFIG.P_USER1_IN_TO_BBB,
    BNC_CONFIG.P_SYNC_IN_TO_BBB,
    BNC_CONFIG.P_REF_IN_TO_BBB,
    BNC_CONFIG.B_USER1_BI_DIR_L3V3,
    BNC_CONFIG.B_USER2_BI_DIR_L3V3,
    BNC_CONFIG.B_VETO_OUT_TO_BBB_L3V3,
    BNC_CONFIG.B_REF_OUT_TO_BBB_L3V3,
    BNC_CONFIG.B_TDC_OUT_TO_BBB_L3V3,
    BNC_CONFIG.B_SYNC_OUT_TO_BBB_L3V3
]

ALLOWED_ANALOG_1V8_PINS = [
    BNC_CONFIG.ADC_5V_C_SENSE_TO_AIN,
    BNC_CONFIG.ADC_3V3_C_SENSE_TO_AIN,
    BNC_CONFIG.VDD_5V_TO_AIN,
    BNC_CONFIG.TR_REF_IN_TO_AIN,
    BNC_CONFIG.TR_SYNC_IN_TO_AIN,
    BNC_CONFIG.TR_USER1_TO_AIN,
    BNC_CONFIG.TR_USER2_TO_AIN
]

ALLOWED_I2C_BUSES = [
    BNC_CONFIG.I2C_IO_EXPANDER_I2CBUS
]

ALLOWED_I2C_CHIP_ADDRESSES = [
    BNC_CONFIG.I2C_IO_EXPANDER_CHIP_ADDRESS
]

ALLOWED_I2C_DATA_ADDRESSES = [
    # Currently unused
    # BNC_CONFIG.I2C_IO_EXPANDER_INPUT_REGISTER,
    BNC_CONFIG.I2C_IO_EXPANDER_CONFIG_REGISTER,
    # Currently unused
    # BNC_CONFIG.I2C_IO_EXPANDER_POLARITY_INVERSION_REGISTER,
    BNC_CONFIG.I2C_IO_EXPANDER_OUTPUT_REGISTER
]
